title: Home
author: Anurag
email: anurag@sharma.space
description: > # this means to ignore newlines until "baseurl:"
  Books, projects and new concepts repository
theme: minima

# social links
github_username:  limo-756 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
